name: CI - Build TUI

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build TUI
    runs-on: x86_64_mojave
    steps:
      - uses: actions/checkout@v2

      - name: Install Python Dependencies
        run: pip3 install --upgrade pyinstaller requests pyobjc

      - run: pyinstaller OpenCore-Patcher.spec
      - run: ./after_pyinstaller.sh
      - run: 'codesign -s "Developer ID Application: Mykola Grymalyuk (S74BDJXQMD)" -v --force --deep --timestamp --entitlements entitlements.plist -o runtime "dist/OpenCore-Patcher.app"'
      - run: cd dist; zip -r ../OpenCore-Patcher-TUI.app.zip OpenCore-Patcher.app
      - run: ./../sign-tui.sh
      - name: Upload App to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenCore-Patcher-TUI.app
          path: OpenCore-Patcher-TUI.app.zip

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenCore-Patcher-TUI.app.zip
          tag: ${{ github.ref }}
          file_glob: true
