name: CI - Build GUI

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build GUI
    runs-on: x86_64_mojave
    steps:
      - uses: actions/checkout@v2

      - run: /Library/Frameworks/Python.framework/Versions/3.9/bin/pyinstaller OpenCore-Patcher.spec
      - run: cd dist; cp OpenCore-Patcher ../; cd ..; mv OpenCore-Patcher OCLP-CLI
      - name: Download latest nightly OCLP-GUI
        run: curl -S -L https://nightly.link/dortania/OCLP-GUI/workflows/build-app/master/OpenCore-Patcher-GUI.app.zip --output ./OpenCore-Patcher-GUI.app.zip --insecure
      - run: unzip -o OpenCore-Patcher-GUI.app.zip
      - run: unzip OpenCore-Patcher-GUI.app.zip; rm OpenCore-Patcher-GUI.app.zip
      - name: Merge new GUI
        run: cp OCLP-CLI OpenCore\ Patcher.app/Contents/Resources/
      - run: python3 merge_gui.py
      - name: Sign Binaries for release
        if: github.event_name == 'release'
        run: |
          'codesign -s "Developer ID Application: Mykola Grymalyuk (S74BDJXQMD)" -v --force --deep --timestamp --entitlements ./payloads/entitlements.plist -o runtime "OpenCore Patcher.app/Contents/Resources/OCLP-CLI"'
          'codesign -s "Developer ID Application: Mykola Grymalyuk (S74BDJXQMD)" -v --force --deep --timestamp --entitlements ./payloads/entitlements.plist -o runtime "OpenCore Patcher.app/Contents/Resources/oclpd"'
          'codesign -s "Developer ID Application: Mykola Grymalyuk (S74BDJXQMD)" -v --force --deep --timestamp --entitlements ./payloads/entitlements.plist -o runtime "OpenCore Patcher.app"'
          ditto -c -k --sequesterRsrc --keepParent OpenCore\ Patcher.app OpenCore-Patcher-GUI.app.zip
          ./../sign-gui.sh
      - name: Upload GUI to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenCore-Patcher-GUI.app
          path: OpenCore-Patcher-GUI.app.zip
      - name: Upload CLI to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OCLP-CLI
          path: OCLP-CLI
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenCore-Patcher-GUI.app.zip
          tag: ${{ github.ref }}
          file_glob: true
      - name: Validate OpenCore
        run: ./OCLP-CLI --validate
