name: CI - Build App

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build App
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      # - name: Install Python Dependencies
      #   run: |
      #     python3 -m pip install -U pip
      #     pip3 install pyinstaller

      - run: pyinstaller OpenCore-Patcher.spec
      - run: ./after_pyinstaller.sh
      - run: 'codesign -s "Developer ID Application: Mykola Grymalyuk (S74BDJXQMD)" -v --deep --timestamp --entitlements entitlements.plist -o runtime "dist/OpenCore-Patcher.app"'

      - run: cd dist; zip ../OpenCore-Patcher.zip OpenCore-Patcher; zip -r ../OpenCore-Patcher.app.zip OpenCore-Patcher.app
      - run: ./../sign-app.sh
      - name: Upload Binary to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenCore-Patcher
          path: OpenCore-Patcher.zip
      - name: Upload App to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenCore-Patcher.app
          path: OpenCore-Patcher.app.zip

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenCore-Patcher.app.zip
          tag: ${{ github.ref }}
          file_glob: true
